#!/usr/bin/env python3

import sys
import argparse
import gpxpy
from geographiclib.geodesic import Geodesic as geodesic

threshold_m = 10000

class PointChecker(object):

    def __init__(self):
        self.previos_point = None

    def check(self, point):
        if self.previos_point is not None:
            distance = geodesic.WGS84.Inverse(
                point.latitude, point.longitude,
                self.previos_point.latitude, self.previos_point.longitude,
                outmask=geodesic.DISTANCE)['s12']
            if distance > threshold_m:
                return False
        self.previos_point = point
        return True

def rm_false_points(gpx_file):
    with open(gpx_file, 'r') as gpx_obj:
        gpx = gpxpy.parse(gpx_obj)
        for track in gpx.tracks:
            for segment in track.segments:
                point_checker = PointChecker()
                segment.points[:] = [p for p in segment.points if point_checker.check(p)]
        output_f = open(gpx_file + '-out.gpx', 'w')
        output_f.write(gpx.to_xml())

def process_files(gpx_files):
    if not gpx_files:
        print('No GPX files specified')
        return

    for gpx_file in gpx_files:
        try:
            rm_false_points(gpx_file)
        except Exception as e:
            print('Error processing "%s":\n\t%s' % (gpx_file, e))
            sys.exit(1)

def make_parser():
    parser = argparse.ArgumentParser(
        usage='%(prog)s [file ...]',
        description='Command line utility to remove false points from gpx file(s)')
    return parser

if __name__ == '__main__':
    args, gpx_files = make_parser().parse_known_args()
    process_files(gpx_files)
